INSERT INTO CATEGORIES VALUES (0, 'Meio Ambiente'),
(1, 'Dicas de Meio Ambiente'),
(2, 'Projetos'),
(3, 'Nossos Projetos'),
(4, 'Outros Projetos'),
(5, 'Entretenimento'),
(6, 'Comida'),
(7, 'Dicas de Comida'),
(8, 'Receitas'),
(9, 'Entenda mais'),
(8, 'Comece aqui')